### ISSUE TITLE
beneficiaries: missing posting authority ?

### ISSUE THREAD

**Issue by fxnormaluser** [steemit/steem-python#9] opened 2017-06-01 20:56 UTC
The beneficiaries argument in post doesn't work for me.

```steembase.exceptions.RPCError: 3030000 tx_missing_posting_auth: missing required posting authority```

I'm using a dictionary for beneficiaries like this: 

```[{'account': 'account1', 'weight': 5000}, {'account': 'account2', 'weight': 5000}]```

Even if I set only the posting account as beneficiary, it returns the same error.

**Comment by Netherdrake** [comment] 2017-06-04 01:32
The json data structure `steem-python` generates seems to be correct, however the bytes output that goes into transaction signing is not, hence the missing authority error.

This suggests there might be a bug somewhere in the serializer, particularly in regards to the `StaticVariant` type.

**Comment by pgarciagon** [comment] 2017-06-17 06:49
Some solution in sight?

**Comment by pgarciagon** [comment] 2017-06-17 06:51
Some solution in sight?

**Comment by fxnormaluser** [comment] 2017-06-23 18:43
I just found out, how it works.

This doesn't work:

```[{'account': 'account1', 'weight': 5000}, {'account': 'account2', 'weight': 5000}]```

This works:

```from collections import OrderedDict```
```[OrderedDict('account': 'account1', 'weight': 5000), OrderedDict('account': 'account2', 'weight': 5000)]```

**Comment by fxnormaluser** [comment] 2017-06-27 19:17
Actually it still doesn't work :/

```
steembase.exceptions.RPCError: 3030000 tx_missing_posting_auth: missing required posting authority
Missing Posting Authority
```

**Comment by oflyhigh** [comment] 2017-06-28 10:40
@Netherdrake 

Hi, Is there some update about this issue?
I encountered the same problem when I tried to post comment with beneficiaries.

Thank you.

**Comment by KylePiira** [comment] 2017-09-04 01:37
The issue is still present I'm going to check to see if piston has some way of solving this.

**Comment by marvin-we** [comment] 2017-10-07 16:00
I had the same issue for [SteemJ](https://github.com/marvin-we/steem-java-api-wrapper) and I can confirm @Netherdrake theory - For me it was related to the byte representation.

You can check my implementation of the byte transformation starting with the `toByteArray` method of the [CommentOptionsOperation](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/core/src/main/java/eu/bittrade/libs/steemj/base/models/operations/CommentOptionsOperation.java) and the [CommentPayoutBeneficiaries](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/core/src/main/java/eu/bittrade/libs/steemj/base/models/CommentPayoutBeneficiaries.java)

I hope that helps a little bit :/ 

Best regards,

@dez1337

**Comment by KylePiira** [comment] 2017-10-07 16:56
Until this issue is fixed in steem-python you can use piston like so:
```
﻿from piston import Steem
s = Steem(keys=[private_posting_key])
s.post(
    title="This is a Test Post",
    body="Hello World this is a test post.",
    author="username",
    meta={
        'extensions': [[0, {
            'beneficiaries': [
                {'account': 'beneficary_account_username', 'weight': 5000},
            ]}
        ]]
    },
    tags=['spam','test']
)

```

**Comment by moisesmcardona** [comment] 2018-01-17 19:32
Still not fixed.

Tried the piston workaround but it doesn't allow me to use other parameters like tags or app.

Would like to see this fixed in this library so that I can fully rely on this library.

**Comment by crokkon** [comment] 2018-01-27 18:46
the following did the trick for me. This is basically copying piston code parts into steem-python. Thanks @KylePiira for the pointer to piston!

```diff
--- steembase/operations.py	2017-09-29 10:11:17.185199365 +0200
+++ steembase/operations.py	2018-01-27 19:39:35.702368032 +0100
@@ -691,12 +691,10 @@
                 kwargs = args[0]
 
             # handle beneficiaries
-            extensions = Array([])
-            beneficiaries = kwargs.get('beneficiaries')
-            if beneficiaries and type(beneficiaries) == list:
-                ext_obj = [0, {'beneficiaries': beneficiaries}]
-                ext = CommentOptionExtensions(ext_obj)
-                extensions = Array([ext])
+            if "extensions" in kwargs and kwargs["extensions"]:
+                extensions = Array([CommentOptionExtensions(o) for o in kwargs["extensions"]])
+            else:
+                extensions = Array([])
 
             super().__init__(OrderedDict([
                 ('author', String(kwargs["author"])),
```

in combination with
```python
ops = [operations.CommentOptions(
    **{"author": author,
       "permlink": permlink,
       "max_accepted_payout": "1000000.000 SBD",
       "percent_steem_dollars": 10000,
       "allow_votes": True,
       "allow_curation_rewards": True,
       'extensions': [[0, {
            'beneficiaries': [
                {'account': beneficiary, 'weight': weight},
            ]}]]
    }
)]
```

This is clearly not a fix, but a workaround. And I'm not sure if it would work with more than one beneficiary...

**Comment by moisesmcardona** [comment] 2018-01-27 20:16
Don't know if I'm doing it right, but on steemd when I push the transaction, all I see in the extensions part is `extensions []`. Seems something is not working right in my case

**Comment by moisesmcardona** [comment] 2018-01-27 20:20
Thanks @crokkon! It worked but what I did was to manually added the beneficiary in the ops code you posted below. I think if that structure is followed, it should work with more than one.

**Comment by emre** [comment] 2018-01-28 14:31
I can confirm @crokkon's workaround works for multiple beneficiaries.

https://steemd.com/tx/ebfaf7cc63a8cd0224acc1eab3d4a726925580be

**Closed** 2018-12-12 20:38 UTC

**Comment by repnox** [comment] 2021-09-11 05:33
My issue is that I was using Anaconda with beem v 0.24.21 but this version apparently has some issue. So instead of using the "conda" command, I had to use pip to install beem 0.24.26 then I stopped getting the error! I hope this helps someone, because I spent multiple days tracking this down!

`pip install beem==0.24.26`
