### ISSUE TITLE
AttributeError: 'Steemd' object has no attribute 'commit' in dex.py

### ISSUE THREAD

**Issue by amosbastian** [steemit/steem-python#120] opened 2018-01-14 11:42 UTC
When using the functions `buy()`, `sell()` and `cancel()` in `dex.py` the following error occurs:
```
AttributeError: 'Steemd' object has no attribute 'commit' in dex.py
```

**Comment by amosbastian** [comment] 2018-01-14 11:45
#121

**Comment by cyon1c** [comment] 2018-03-07 18:34
Duplicate of #121 .

**Closed by cyon1c** 2018-03-07 18:34 UTC
