### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3k9th27l/steem/

### ISSUE THREAD

**Issue by enki74** [steemit/steem-python#82] opened 2017-10-16 22:48 UTC
(steemit_env) telesti@starship:~/python$ pip install -U steem
Collecting steem
  Using cached steem-0.18.103.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3k9th27l/steem/setup.py", line 10, in <module>
        assert sys.version_info[0] == package_meta.required_python_major and sys.version_info[1] >= package_meta.required_python_minor, "%s requires Python %s or newer" % (package_meta.package_name, package_meta.required_python_ver)
    AssertionError: steem requires Python 3.6 or newer
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3k9th27l/steem/

**Comment by drov0** [comment] 2017-10-18 09:37
AssertionError: steem requires Python 3.6 or newer

You need python 3.6

**Comment by GarethNelson** [comment] 2017-10-18 16:47
As drov0 stated, the package now requires python 3.6.

3.6 is not in most distro package repos yet, please take a look here:
https://www.python.org/downloads/release/python-363/

Personally I find it best to install from source and use "make altinstall" to avoid compatibility issues with existing python install.

**Comment by enki74** [comment] 2017-10-19 14:54
Thanks I think I got this part done

**Comment by GarethNelson** [comment] 2017-10-19 17:34
Closing this as duplicate of other issue, see my response there regarding sqlite3

**Closed by GarethNelson** 2017-10-19 17:34 UTC
