### ISSUE TITLE
Steempy Addkey

### ISSUE THREAD

**Issue by that1consultant** [steemit/steem-python#51] opened 2017-09-14 01:50 UTC
Learning my way around and getting the following error for the steem conductor Wallet installation

https://steemit.com/steem/@furion/introducing-conductor-a-simple-steem-witness-toolkit

root@steemWitness123:~# steempy addkey
Traceback (most recent call last):
  File "/usr/local/bin/steempy", line 9, in <module>
    load_entry_point('steem==0.18.93', 'console_scripts', 'steempy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in                                                                                                          load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in                                                                                                          load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in                                                                                                          load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in                                                                                                          resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/steem/__init__.py", line 2, in <m                                                                                                         odule>
    from .steem import Steem
  File "/usr/local/lib/python3.5/dist-packages/steem/steem.py", line 1, in <modu                                                                                                         le>
    from .commit import Commit
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 20, in <mo                                                                                                         dule>
    from .account import Account
  File "/usr/local/lib/python3.5/dist-packages/steem/account.py", line 8, in <mo                                                                                                         dule>
    from funcy.simple_funcs import rpartial
ImportError: No module named 'funcy.simple_funcs'
root@steemWitness1223:~#

**Comment by sneak** [comment] 2017-09-24 10:35
dupe of #50

**Closed by sneak** 2017-09-24 10:35 UTC
